"""
Video Renderer (V3)

Scene-based video rendering.

For each scene:

    fixed image
        +
    scene narration
        +
    scene subtitles
        ↓
    scene_video.mp4

Final render:

    scene1.mp4
    scene2.mp4
    scene3.mp4
    scene4.mp4
        +
    background music
        ↓
    final_video.mp4

Images are NEVER generated by this module.
"""

from pathlib import Path
import subprocess
from typing import Optional

from config import (
    FFMPEG_PATH,
    FFPROBE_PATH,
    BACKGROUND_MUSIC,
    BACKGROUND_MUSIC_VOLUME,
    VIDEO_WIDTH,
    VIDEO_HEIGHT,
    FPS,
)

from modules.logger import Logger


class VideoRenderer:

    # ==========================================================
    # SBG SUBTITLE STYLE
    # ==========================================================

    # Large enough for 1080x1920 Shorts
    SUBTITLE_FONT = "Noto Sans Devanagari"

    SUBTITLE_FONT_SIZE = 54

    SUBTITLE_BOLD = True

    # ASS uses BGR/hex formatting internally.
    # FFFFFF = white
    SUBTITLE_PRIMARY_COLOUR = "&H00E6F3FF"

    # Black outline
    SUBTITLE_OUTLINE_COLOUR = "&H00120A05"

    # Slightly transparent black shadow
    SUBTITLE_SHADOW_COLOUR = "&H90000000"

    # Thick cinematic outline
    SUBTITLE_OUTLINE = 3

    # Shadow depth
    SUBTITLE_SHADOW = 3

    # 2 = centered
    SUBTITLE_ALIGNMENT = 2

    # Distance from bottom of video.
    #
    # 400-ish places subtitles in the lower-middle
    # rather than directly above YouTube controls.
    SUBTITLE_MARGIN_V = 330

    # Horizontal margins
    SUBTITLE_MARGIN_L = 100
    SUBTITLE_MARGIN_R = 100

    # ==========================================================
    # INITIALIZE
    # ==========================================================

    def __init__(self):

        self.ffmpeg = str(
            FFMPEG_PATH
        )

        self.ffprobe = str(
            FFPROBE_PATH
        )

    # ==========================================================
    # AUDIO DURATION
    # ==========================================================

    def _audio_duration(
        self,
        audio_file: Path,
    ) -> float:

        audio_file = Path(
            audio_file
        )

        command = [

            self.ffprobe,
            "-hide_banner",
            "-loglevel", "error",
            "-v",
            "error",

            "-show_entries",
            "format=duration",

            "-of",
            "default="
            "noprint_wrappers=1:"
            "nokey=1",

            str(audio_file),
        ]

        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            check=True,
        )

        value = (
            result.stdout
            .strip()
        )

        if not value:

            raise Exception(
                f"Could not determine audio duration:\n"
                f"{audio_file}"
            )

        duration = float(
            value
        )

        if duration <= 0:

            raise Exception(
                f"Audio has zero duration:\n"
                f"{audio_file}"
            )

        return duration

    # ==========================================================
    # Video DURATION
    # ==========================================================

    def _video_duration(
        self,
        video_file,
    ):
        """
        Return the exact duration of a video file in seconds.

        Uses FFprobe so the duration comes from the actual
        rendered scene video.
        """

        video_file = Path(
            video_file
        )

        if not video_file.exists():
            raise FileNotFoundError(
                f"Video file not found:\n"
                f"{video_file}"
            )

        command = [
            self.ffprobe,
            "-v",
            "error",
            "-show_entries",
            "format=duration",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
            str(video_file),
        ]

        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            check=True,
        )

        duration_text = (
            result.stdout.strip()
        )

        if not duration_text:
            raise RuntimeError(
                f"FFprobe returned no duration for:\n"
                f"{video_file}"
            )

        duration = float(
            duration_text
        )

        if duration <= 0:
            raise RuntimeError(
                f"Invalid video duration "
                f"{duration:.6f}s:\n"
                f"{video_file}"
            )

        return duration


    # ==========================================================
    # CHECK FILE
    # ==========================================================

    def _check_file(
        self,
        file_path,
        description,
    ):

        file_path = Path(
            file_path
        )

        if not file_path.exists():

            raise FileNotFoundError(
                f"{description} not found:\n"
                f"{file_path}"
            )

        if file_path.stat().st_size <= 0:

            raise Exception(
                f"{description} is empty:\n"
                f"{file_path}"
            )

        return file_path

    # ==========================================================
    # ESCAPE FILTER PATH
    # ==========================================================

    def _escape_filter_path(
        self,
        file_path,
    ):

        path = str(
            Path(
                file_path
            ).resolve()
        )

        path = path.replace(
            "\\",
            "/",
        )

        path = path.replace(
            ":",
            "\\:",
        )

        path = path.replace(
            "'",
            "\\'",
        )

        return path

    # ==========================================================
    # PRINT FFMPEG COMMAND
    # ==========================================================

    def _print_command(
        self,
        command,
    ):

        print()
        print("=" * 80)
        print("FFMPEG COMMAND")
        print("=" * 80)

        print(
            " ".join(
                (
                    f'"{item}"'
                    if " " in str(item)
                    else str(item)
                )
                for item in command
            )
        )

        print("=" * 80)
        print()


    # ==========================================================
    # SRT → ASS TIME
    # ==========================================================

    def _srt_to_ass_time(
        self,
        value,
    ):

        value = value.strip()

        # SRT:
        #
        # 00:00:02,500
        #
        # ASS:
        #
        # 0:00:02.50

        parts = value.split(
            ":"
        )

        if len(parts) != 3:

            raise ValueError(
                f"Invalid SRT timestamp: {value}"
            )

        hours = int(
            parts[0]
        )

        minutes = int(
            parts[1]
        )

        seconds_part = parts[2]

        if "," in seconds_part:

            seconds, milliseconds = (
                seconds_part.split(
                    ",",
                    1,
                )
            )

        else:

            seconds = seconds_part
            milliseconds = "0"

        seconds = int(
            seconds
        )

        milliseconds = int(
            milliseconds.ljust(
                3,
                "0",
            )[:3]
        )

        centiseconds = int(
            round(
                milliseconds
                / 10
            )
        )

        # Handle rounding to 100 centiseconds.
        if centiseconds >= 100:

            centiseconds = 0
            seconds += 1

        if seconds >= 60:

            seconds = 0
            minutes += 1

        if minutes >= 60:

            minutes = 0
            hours += 1

        return (
            f"{hours}:"
            f"{minutes:02d}:"
            f"{seconds:02d}."
            f"{centiseconds:02d}"
        )


    # ==========================================================
    # CREATE NARRATION KARAOKE ASS
    # ==========================================================

    def _create_narration_karaoke_ass(
        self,
        narration_json,
        ass_file,
    ):
        """
        Create an ASS karaoke subtitle file from narration.json.

        The narration.json word timings are the source of truth.

        ASS karaoke behaviour:

            Future words   = white
            Spoken words   = turquoise

        This creates ONE subtitle layer only.
        """

        import json

        narration_json = Path(
            narration_json
        )

        ass_file = Path(
            ass_file
        )

        # ======================================================
        # LOAD JSON
        # ======================================================

        with open(
            narration_json,
            "r",
            encoding="utf-8",
        ) as f:

            data = json.load(f)

        words = data.get(
            "words",
            []
        )

        if not words:

            raise ValueError(
                "No word timings found in narration.json:\n"
                f"{narration_json}"
            )

        # ======================================================
        # CLEAN WORDS
        # ======================================================

        cleaned_words = []

        for entry in words:

            text = str(
                entry.get(
                    "text",
                    "",
                )
            ).strip()

            if not text:
                continue

            start = float(
                entry.get(
                    "start",
                    0,
                )
            )

            end = float(
                entry.get(
                    "end",
                    0,
                )
            )

            if end <= start:
                continue

            cleaned_words.append(
                {
                    "text": text,
                    "start": start,
                    "end": end,
                }
            )

        if not cleaned_words:

            raise ValueError(
                "Narration JSON contains no valid "
                "word timings:\n"
                f"{narration_json}"
            )

        # ======================================================
        # ASS TIME FORMAT
        # ======================================================

        def ass_time(seconds):

            seconds = max(
                0.0,
                float(seconds),
            )

            hours = int(
                seconds // 3600
            )

            minutes = int(
                (seconds % 3600)
                // 60
            )

            secs = (
                seconds
                - (hours * 3600)
                - (minutes * 60)
            )

            return (
                f"{hours}:"
                f"{minutes:02d}:"
                f"{secs:05.2f}"
            )

        # ======================================================
        # TURQUOISE
        #
        # ASS uses BGR hexadecimal.
        #
        # Desired RGB:
        #       64, 224, 208
        #
        # ASS:
        #       &H00D0E040
        # ======================================================

        turquoise = (
            "&H00D0E040"
        )

        white = (
            "&H00FFFFFF"
        )

        outline = (
            "&H00120A05"
        )

        shadow = (
            "&H80000000"
        )

        # ======================================================
        # FONT
        # ======================================================

        font_name = (
            "Noto Sans"
        )

        # ======================================================
        # BUILD ASS
        # ======================================================

        lines = []

        lines.append(
            "[Script Info]"
        )

        lines.append(
            "ScriptType: v4.00+"
        )

        lines.append(
            "PlayResX: 1080"
        )

        lines.append(
            "PlayResY: 1920"
        )

        lines.append(
            "ScaledBorderAndShadow: yes"
        )

        lines.append(
            ""
        )

        lines.append(
            "[V4+ Styles]"
        )

        lines.append(
            "Format: "
            "Name, Fontname, Fontsize, "
            "PrimaryColour, SecondaryColour, "
            "OutlineColour, BackColour, "
            "Bold, Italic, Underline, StrikeOut, "
            "ScaleX, ScaleY, Spacing, Angle, "
            "BorderStyle, Outline, Shadow, "
            "Alignment, MarginL, MarginR, MarginV, Encoding"
        )

        lines.append(
            "Style: Default,"
            f"{font_name},"
            "54,"
            f"{turquoise},"
            f"{white},"
            f"{outline},"
            f"{shadow},"
            "0,0,0,0,"
            "100,100,0,0,"
            "1,3,2,"
            "2,80,80,545,1"
        )

        lines.append(
            ""
        )

        lines.append(
            "[Events]"
        )

        lines.append(
            "Format: "
            "Layer, Start, End, Style, "
            "Name, MarginL, MarginR, MarginV, "
            "Effect, Text"
        )

        # ======================================================
        # BUILD WORD-BY-WORD KARAOKE EVENTS
        # ======================================================

        for i, word in enumerate(
            cleaned_words
        ):

            start = word["start"]

            # --------------------------------------------------
            # Determine end.
            #
            # Each event lasts from this word's start until
            # the next word starts.
            #
            # This prevents gaps between words.
            # --------------------------------------------------

            if i + 1 < len(
                cleaned_words
            ):

                end = max(
                    word["end"],
                    cleaned_words[
                        i + 1
                    ]["start"],
                )

            else:

                end = word["end"]

            # --------------------------------------------------
            # Build complete sentence.
            #
            # We use ASS karaoke tags so the currently spoken
            # word is turquoise while future words remain white.
            # --------------------------------------------------

            karaoke_parts = []

            for j, current in enumerate(
                cleaned_words
            ):

                text = current[
                    "text"
                ]

                # Escape ASS special characters.
                text = (
                    text
                    .replace(
                        "\\",
                        "\\\\",
                    )
                    .replace(
                        "{",
                        "\\{",
                    )
                    .replace(
                        "}",
                        "\\}",
                    )
                )

                # ----------------------------------------------
                # Duration of this word in centiseconds.
                # ----------------------------------------------

                word_duration = max(
                    1,
                    round(
                        (
                            current["end"]
                            - current["start"]
                        )
                        * 100
                    ),
                )

                # ------------------------------------------------
                # ASS \k:
                #
                # SecondaryColour is shown before the karaoke
                # timing is reached.
                #
                # PrimaryColour is shown after it is reached.
                #
                # We deliberately use:
                #
                # Primary   = turquoise
                # Secondary = white
                #
                # Therefore the spoken portion becomes turquoise.
                # ------------------------------------------------

                karaoke_parts.append(
                    f"{{\\k{word_duration}}}"
                    f"{text}"
                )

                if j < len(
                    cleaned_words
                ) - 1:

                    karaoke_parts.append(
                        " "
                    )

            subtitle_text = (
                "".join(
                    karaoke_parts
                )
            )

            lines.append(
                "Dialogue: 0,"
                f"{ass_time(start)},"
                f"{ass_time(end)},"
                "Default,,"
                "0,0,0,"
                "0,"
                ","
                f"{subtitle_text}"
            )

        # ======================================================
        # WRITE FILE
        # ======================================================

        ass_file.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        with open(
            ass_file,
            "w",
            encoding="utf-8-sig",
        ) as f:

            f.write(
                "\n".join(
                    lines
                )
            )

        Logger.success(
            "Narration karaoke ASS created -> "
            f"{ass_file}"
        )

        Logger.info(
            f"Karaoke words : "
            f"{len(cleaned_words)}"
        )


    # ==========================================================
    # GENERIC WORD-BY-WORD SUBTITLE OVERLAY
    # ==========================================================

    def _create_word_highlight_overlay(
        self,
        narration_json,
        output_dir,
        duration,
    ):
        """
        Create a transparent PNG frame sequence containing
        word-by-word subtitle highlighting.

        Behaviour
        ---------
        - Reads narration.json
        - Uses narration.json word timings as the source of truth
        - Splits grouped words
        - Allocates grouped timing proportionally
        - Displays all subtitle words
        - Exactly ONE spoken word is turquoise
        - Other words are white
        - During pauses, the last spoken word remains turquoise
        - Automatically wraps subtitles inside a safe screen area
        - Works for English / Hindi / Sanskrit
        """

        import json
        import re
        import shutil

        from PIL import (
            Image,
            ImageDraw,
            ImageFont,
        )

        # ======================================================
        # CONSTANTS
        # ======================================================

        width = VIDEO_WIDTH
        height = VIDEO_HEIGHT
        fps = FPS

        # ------------------------------------------------------
        # Subtitle safe area
        # ------------------------------------------------------

        max_text_width = 900

        bottom_margin = 300

        line_spacing = 12

        # ------------------------------------------------------
        # Font
        # ------------------------------------------------------

        font_candidates = [

            Path(
                "assets/fonts/"
                "NotoSansDevanagari-Regular.ttf"
            ),

            Path(
                "assets/fonts/"
                "NotoSansDevanagari/"
                "NotoSansDevanagari-Regular.ttf"
            ),

        ]

        font_file = None

        for candidate in font_candidates:

            if candidate.exists():

                font_file = candidate
                break

        if font_file is None:

            raise FileNotFoundError(
                "Noto Sans Devanagari font was not found.\n"
                "Expected:\n"
                "assets/fonts/NotoSansDevanagari-Regular.ttf"
            )

        # ------------------------------------------------------
        # Font sizes
        # ------------------------------------------------------

        font_size = 54

        font = ImageFont.truetype(
            str(font_file),
            font_size,
        )

        # ------------------------------------------------------
        # Colours
        #
        # PIL uses RGB.
        # ------------------------------------------------------

        WHITE = (
            255,
            255,
            255,
        )

        TURQUOISE = (
            0,
            230,
            243,
        )

        OUTLINE = (
            18,
            10,
            5,
        )

        # ======================================================
        # LOAD JSON
        # ======================================================

        with open(
            narration_json,
            "r",
            encoding="utf-8",
        ) as f:

            narration_data = json.load(f)

        raw_words = narration_data.get(
            "words",
            [],
        )

        if not raw_words:

            raise ValueError(
                "No word timings found in:\n"
                f"{narration_json}"
            )

        # ======================================================
        # BUILD INDIVIDUAL WORD TIMINGS
        # ======================================================

        words = []

        punctuation_only = re.compile(
            r"^[।॥,.;:!?।॥]+$"
        )

        for entry in raw_words:

            raw_text = str(
                entry.get(
                    "text",
                    "",
                )
            ).strip()

            if not raw_text:
                continue

            try:

                start = float(
                    entry["start"]
                )

                end = float(
                    entry["end"]
                )

            except (
                KeyError,
                TypeError,
                ValueError,
            ):

                continue

            if end < start:
                end = start

            # --------------------------------------------------
            # Split grouped narration entries.
            #
            # Example:
            #
            # "धर्मक्षेत्रे कुरुक्षेत्रे"
            #
            # becomes:
            #
            # धर्मक्षेत्रे
            # कुरुक्षेत्रे
            # --------------------------------------------------

            tokens = raw_text.split()

            if not tokens:
                continue

            # --------------------------------------------------
            # Punctuation-only tokens should NOT become their
            # own highlighted word.
            #
            # Example:
            #
            # "सञ्जय ॥"
            #
            # becomes:
            #
            # "सञ्जय ॥"
            #
            # with one timing.
            # --------------------------------------------------

            cleaned_tokens = []

            for token in tokens:

                if punctuation_only.match(
                    token
                ):

                    if cleaned_tokens:

                        cleaned_tokens[-1][
                            "display"
                        ] += token

                    continue

                cleaned_tokens.append(
                    {
                        "display": token,
                        "raw": token,
                    }
                )

            if not cleaned_tokens:
                continue

            # --------------------------------------------------
            # Allocate timing proportionally.
            #
            # Longer words receive proportionally more time.
            # --------------------------------------------------

            total_length = sum(
                max(
                    1,
                    len(
                        item["raw"]
                    ),
                )
                for item in cleaned_tokens
            )

            total_duration = (
                end - start
            )

            current_time = start

            for item in cleaned_tokens:

                word_length = max(
                    1,
                    len(
                        item["raw"]
                    ),
                )

                portion = (
                    word_length
                    / total_length
                )

                word_duration = (
                    total_duration
                    * portion
                )

                word_start = (
                    current_time
                )

                word_end = (
                    current_time
                    + word_duration
                )

                words.append(
                    {
                        "text": item[
                            "display"
                        ],
                        "start": word_start,
                        "end": word_end,
                    }
                )

                current_time = word_end

        if not words:

            raise ValueError(
                "Could not create usable word timings from:\n"
                f"{narration_json}"
            )

        # ======================================================
        # NORMALIZE TIMINGS
        # ======================================================

        words.sort(
            key=lambda item:
            item["start"]
        )

        for word in words:

            word["start"] = max(
                0.0,
                min(
                    float(
                        word["start"]
                    ),
                    duration,
                ),
            )

            word["end"] = max(
                word["start"],
                min(
                    float(
                        word["end"]
                    ),
                    duration,
                ),
            )

        # ======================================================
        # LOG
        # ======================================================

        Logger.error(
            f"Subtitle words : "
            f"{len(words)}"
        )

        for word in words:

            Logger.error(
                f"  {word['text']} "
                f"{word['start']:.3f} -> "
                f"{word['end']:.3f}"
            )

        # ======================================================
        # PREPARE OUTPUT DIRECTORY
        # ======================================================

        output_dir = Path(
            output_dir
        )

        output_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        # ------------------------------------------------------
        # Remove old frames.
        # ------------------------------------------------------

        for old_file in output_dir.glob(
            "frame_*.png"
        ):

            try:

                old_file.unlink()

            except OSError:
                pass

        # ======================================================
        # TEXT MEASUREMENT HELPERS
        # ======================================================

        def text_width(
            draw,
            text,
        ):

            if not text:
                return 0

            bbox = draw.textbbox(
                (0, 0),
                text,
                font=font,
                stroke_width=0,
            )

            return (
                bbox[2] - bbox[0]
            )

        # ======================================================
        # WRAP WORDS
        # ======================================================

        def wrap_words(
            draw,
            active_index,
        ):
            """
            Wrap the complete narration into lines while keeping
            words together.

            The active word is NOT allowed to affect wrapping.
            """

            lines = []

            current_line = []

            current_width = 0

            for index, word in enumerate(
                words
            ):

                text = word[
                    "text"
                ]

                word_width = text_width(
                    draw,
                    text,
                )

                space_width = text_width(
                    draw,
                    " ",
                )

                proposed_width = (
                    word_width
                    if not current_line
                    else
                    current_width
                    + space_width
                    + word_width
                )

                if (
                    current_line
                    and proposed_width
                    > max_text_width
                ):

                    lines.append(
                        current_line
                    )

                    current_line = [
                        index
                    ]

                    current_width = (
                        word_width
                    )

                else:

                    current_line.append(
                        index
                    )

                    current_width = (
                        proposed_width
                    )

            if current_line:

                lines.append(
                    current_line
                )

            return lines

        # ======================================================
        # DETERMINE ACTIVE WORD
        # ======================================================

        def get_active_word(
            current_time,
        ):
            """
            Return the word that should currently be turquoise.

            During a pause, the previous spoken word remains
            active until the next word starts.
            """

            active = None

            for index, word in enumerate(
                words
            ):

                if (
                    word["start"]
                    <= current_time
                ):

                    active = index

                else:

                    break

            return active

        # ======================================================
        # DRAW ONE FRAME
        # ======================================================

        def draw_frame(
            frame_time,
        ):

            image = Image.new(
                "RGBA",
                (
                    width,
                    height,
                ),
                (
                    0,
                    0,
                    0,
                    0,
                ),
            )

            draw = ImageDraw.Draw(
                image
            )

            active_index = (
                get_active_word(
                    frame_time
                )
            )

            lines = wrap_words(
                draw,
                active_index,
            )

            # --------------------------------------------------
            # Calculate total subtitle height
            # --------------------------------------------------

            line_heights = []

            for line in lines:

                bbox = draw.textbbox(
                    (0, 0),
                    "Ag",
                    font=font,
                    stroke_width=0,
                )

                line_heights.append(
                    bbox[3] - bbox[1]
                )

            total_height = (
                sum(
                    line_heights
                )
                + (
                    line_spacing
                    * max(
                        0,
                        len(lines) - 1,
                    )
                )
            )

            # --------------------------------------------------
            # Vertically center the subtitle block around the
            # bottom safe area.
            # --------------------------------------------------

            start_y = (
                height
                - bottom_margin
                - total_height
            )

            # Never allow the subtitle block above the image.

            start_y = max(
                100,
                start_y,
            )

            # --------------------------------------------------
            # Draw each line
            # --------------------------------------------------

            current_y = start_y

            for line_index, line in enumerate(
                lines
            ):

                # ----------------------------------------------
                # Calculate line width
                # ----------------------------------------------

                line_width = 0

                for position, word_index in enumerate(
                    line
                ):

                    word_text = words[
                        word_index
                    ]["text"]

                    line_width += text_width(
                        draw,
                        word_text,
                    )

                    if position < (
                        len(line) - 1
                    ):

                        line_width += (
                            text_width(
                                draw,
                                " ",
                            )
                        )

                # ----------------------------------------------
                # Center line horizontally
                # ----------------------------------------------

                x = (
                    width
                    - line_width
                ) / 2

                # ----------------------------------------------
                # Draw words
                # ----------------------------------------------

                for position, word_index in enumerate(
                    line
                ):

                    word_text = words[
                        word_index
                    ]["text"]

                    if (
                        word_index
                        == active_index
                    ):

                        fill = TURQUOISE

                    else:

                        fill = WHITE

                    # ------------------------------------------
                    # Text outline
                    # ------------------------------------------

                    draw.text(
                        (
                            x,
                            current_y,
                        ),
                        word_text,
                        font=font,
                        fill=fill,
                        stroke_width=3,
                        stroke_fill=OUTLINE,
                    )

                    x += text_width(
                        draw,
                        word_text,
                    )

                    if position < (
                        len(line) - 1
                    ):

                        x += text_width(
                            draw,
                            " ",
                        )

                current_y += (
                    line_heights[
                        line_index
                    ]
                    + line_spacing
                )

            return image

        # ======================================================
        # GENERATE FRAMES
        # ======================================================

        total_frames = max(
            1,
            int(
                round(
                    duration
                    * fps
                )
            ),
        )

        Logger.info(
            "Generating subtitle overlay "
            f"frames : {total_frames}"
        )

        for frame_number in range(
            total_frames
        ):

            frame_time = (
                frame_number
                / fps
            )

            frame = draw_frame(
                frame_time
            )

            frame_path = (
                output_dir
                / (
                    f"frame_"
                    f"{frame_number:06d}"
                    f".png"
                )
            )

            frame.save(
                frame_path,
                "PNG",
            )

        # ======================================================
        # FINAL FRAME
        #
        # Ensure the last frame covers the exact end of audio.
        # ======================================================

        if total_frames > 0:

            final_frame = draw_frame(
                max(
                    0.0,
                    duration
                    - (
                        1
                        / fps
                    ),
                )
            )

            final_frame.save(
                output_dir
                / (
                    f"frame_"
                    f"{total_frames - 1:06d}"
                    f".png"
                ),
                "PNG",
            )

        Logger.success(
            "Word-highlight subtitle frames "
            f"created -> {output_dir}"
        )

        return output_dir

    # ==========================================================
    # RENDER ONE SCENE
    # ==========================================================

    def render_scene(
        self,
        image_file,
        audio_file,
        subtitle_file=None,
        narration_json=None,
        output_file=None,
    ):
        """
        Render one scene using the generic transparent
        word-highlight overlay.

        SAME FUNCTION FOR:

            Scene 1
            Scene 2
            Scene 3
            Scene 4

        Source of truth:

            narration.json

        Subtitle behaviour:

            WHITE WHITE TURQUOISE WHITE

        Exactly one currently spoken word is turquoise.

        During narration pauses, the last spoken word remains
        turquoise until the next spoken word begins.
        """

        import subprocess

        # ======================================================
        # VALIDATE INPUTS
        # ======================================================

        image_file = self._check_file(
            image_file,
            "Scene image",
        )

        audio_file = self._check_file(
            audio_file,
            "Scene narration",
        )

        if narration_json is None:

            raise ValueError(
                "narration_json is required."
            )

        narration_json = self._check_file(
            narration_json,
            "Narration JSON",
        )

        # ======================================================
        # OUTPUT
        # ======================================================

        if output_file is None:

            output_file = (
                Path(image_file).parent
                / "scene_video.mp4"
            )

        output_file = Path(
            output_file
        )

        output_file.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        # ======================================================
        # AUDIO DURATION
        # ======================================================

        duration = self._audio_duration(
            audio_file
        )

        Logger.info(
            f"Scene duration : "
            f"{duration:.3f}s"
        )

        # ======================================================
        # SUBTITLE FRAME DIRECTORY
        # ======================================================

        overlay_dir = (
            output_file.parent
            / "_subtitle_frames"
        )

        # ======================================================
        # CREATE GENERIC WORD-HIGHLIGHT OVERLAY
        # ======================================================

        self._create_word_highlight_overlay(
            narration_json=str(
                narration_json
            ),
            output_dir=str(
                overlay_dir
            ),
            duration=duration,
        )

        # ======================================================
        # INPUT PATTERN
        # ======================================================

        input_pattern = (
            overlay_dir
            / "frame_%06d.png"
        )

        if not input_pattern.parent.exists():

            raise FileNotFoundError(
                "Subtitle frame directory "
                "was not created:\n"
                f"{overlay_dir}"
            )

        # ======================================================
        # FFMPEG FILTER
        # ======================================================
        #
        # Input 0:
        #     static scene image
        #
        # Input 1:
        #     narration
        #
        # Input 2:
        #     transparent subtitle PNG sequence
        #
        # Image + subtitle overlay
        #         ↓
        #     final scene video
        #
        # ======================================================

        video_filter = (

            # ----------------------------------------------
            # Background image
            # ----------------------------------------------

            f"[0:v]"
            f"scale="
            f"{VIDEO_WIDTH}:"
            f"{VIDEO_HEIGHT}:"
            f"force_original_aspect_ratio=decrease,"
            f"pad="
            f"{VIDEO_WIDTH}:"
            f"{VIDEO_HEIGHT}:"
            f"(ow-iw)/2:"
            f"(oh-ih)/2,"
            f"fps={FPS},"
            f"format=rgba"
            f"[bg];"

            # ----------------------------------------------
            # Subtitle overlay
            # ----------------------------------------------

            f"[2:v]"
            f"format=rgba"
            f"[sub];"

            # ----------------------------------------------
            # Overlay
            # ----------------------------------------------

            f"[bg][sub]"
            f"overlay="
            f"0:0:"
            f"shortest=1,"
            f"format=yuv420p"
            f"[v]"
        )

        # ======================================================
        # FFMPEG COMMAND
        # ======================================================

        command = [

            self.ffmpeg,

            "-hide_banner",

            "-loglevel",
            "error",

            "-y",

            # ==================================================
            # INPUT 0 — IMAGE
            # ==================================================

            "-loop",
            "1",

            "-i",
            str(image_file),

            # ==================================================
            # INPUT 1 — NARRATION
            # ==================================================

            "-i",
            str(audio_file),

            # ==================================================
            # INPUT 2 — TRANSPARENT SUBTITLE FRAMES
            # ==================================================

            "-framerate",
            str(FPS),

            "-i",
            str(input_pattern),

            # ==================================================
            # FILTER
            # ==================================================

            "-filter_complex",
            video_filter,

            # ==================================================
            # MAP
            # ==================================================

            "-map",
            "[v]",

            "-map",
            "1:a",

            # ==================================================
            # VIDEO
            # ==================================================

            "-c:v",
            "libx264",

            "-preset",
            "medium",

            "-crf",
            "18",

            "-pix_fmt",
            "yuv420p",

            # ==================================================
            # AUDIO
            # ==================================================

            "-c:a",
            "aac",

            "-b:a",
            "192k",

            "-ar",
            "48000",

            # ==================================================
            # EXACT DURATION
            # ==================================================

            "-t",
            f"{duration:.6f}",

            # ==================================================
            # MP4
            # ==================================================

            "-movflags",
            "+faststart",

            str(output_file),
        ]

        # ======================================================
        # PRINT COMMAND
        # ======================================================

        self._print_command(
            command
        )

        Logger.info(
            f"Rendering scene -> "
            f"{output_file}"
        )

        # ======================================================
        # RUN FFMPEG
        # ======================================================

        subprocess.run(
            command,
            check=True,
        )

        # ======================================================
        # VERIFY
        # ======================================================

        if not output_file.exists():

            raise Exception(
                "FFmpeg completed but scene "
                "video was not created:\n"
                f"{output_file}"
            )

        if output_file.stat().st_size <= 0:

            raise Exception(
                f"Scene video is empty:\n"
                f"{output_file}"
            )

        Logger.success(
            f"Scene video saved -> "
            f"{output_file}"
        )

        return output_file
    
    
    # ==========================================================
    # MERGE SCENE VIDEOS
    # ==========================================================

    def merge_scenes(
        self,
        scene_videos,
        verse_folder,
    ):
        """
        Merge the four independently rendered scene videos
        using smooth video + audio crossfades.

        Scene architecture:

            Scene 1
                ↓
            0.5s crossfade
                ↓
            Scene 2
                ↓
            0.5s crossfade
                ↓
            Scene 3
                ↓
            0.5s crossfade
                ↓
            Scene 4

        The individual scene videos already contain:

            image
            narration
            subtitles
            word highlighting

        This function only joins them smoothly.

        Background music is added later by the pipeline.
        """

        # ==========================================================
        # VALIDATE
        # ==========================================================

        if not scene_videos:
            raise ValueError(
                "No scene videos were supplied."
            )

        scene_videos = [
            Path(video)
            for video in scene_videos
        ]

        for index, video in enumerate(
            scene_videos,
            start=1,
        ):

            if not video.exists():

                raise FileNotFoundError(
                    f"Scene {index} video not found:\n"
                    f"{video}"
                )

            if video.stat().st_size <= 0:

                raise ValueError(
                    f"Scene {index} video is empty:\n"
                    f"{video}"
                )

        # ==========================================================
        # OUTPUT
        # ==========================================================

        verse_folder = Path(
            verse_folder
        )

        final_folder = (
            verse_folder
            / "final"
        )

        final_folder.mkdir(
            parents=True,
            exist_ok=True,
        )

        output_file = (
            final_folder
            / "merged_video.mp4"
        )

        # ==========================================================
        # TRANSITION SETTINGS
        # ==========================================================

        TRANSITION_DURATION = 0.5

        Logger.info(
            "Using smooth scene transitions:"
        )

        Logger.info(
            f"Crossfade duration : "
            f"{TRANSITION_DURATION:.2f}s"
        )

        # ==========================================================
        # GET SCENE DURATIONS
        # ==========================================================

        durations = []

        for index, video in enumerate(
            scene_videos,
            start=1,
        ):

            duration = (
                self._video_duration(
                    video
                )
            )

            if duration <= 0:

                raise ValueError(
                    f"Could not determine duration "
                    f"of Scene {index}:\n"
                    f"{video}"
                )

            durations.append(
                duration
            )

            Logger.info(
                f"Scene {index} duration : "
                f"{duration:.3f}s"
            )

        # ==========================================================
        # SAFETY CHECK
        # ==========================================================

        for index, duration in enumerate(
            durations,
            start=1,
        ):

            if duration <= TRANSITION_DURATION:

                raise ValueError(
                    f"Scene {index} is only "
                    f"{duration:.3f}s long, which is too short "
                    f"for a {TRANSITION_DURATION:.3f}s transition."
                )

        # ==========================================================
        # BUILD INPUTS
        # ==========================================================

        command = [

            self.ffmpeg,

            "-hide_banner",
            "-loglevel", "error",
            "-y",
        ]

        for video in scene_videos:

            command.extend(
                [
                    "-i",
                    str(video),
                ]
            )

        # ==========================================================
        # BUILD VIDEO XFADE FILTER
        # ==========================================================

        filter_parts = []

        # First transition:
        #
        # Scene 1 duration = D1
        #
        # xfade starts at:
        #
        # D1 - transition
        #
        # Example:
        #
        # D1 = 10.0
        # transition = 0.5
        #
        # offset = 9.5
        # ==========================================================

        current_video = "[0:v]"

        accumulated_duration = durations[0]

        for index in range(
            1,
            len(scene_videos),
        ):

            next_video = (
                f"[{index}:v]"
            )

            output_label = (
                f"[v{index}]"
            )

            offset = (
                accumulated_duration
                - TRANSITION_DURATION
            )

            filter_parts.append(
                f"{current_video}"
                f"{next_video}"
                f"xfade="
                f"transition=fade:"
                f"duration={TRANSITION_DURATION:.3f}:"
                f"offset={offset:.3f}"
                f"{output_label}"
            )

            current_video = (
                output_label
            )

            accumulated_duration = (
                accumulated_duration
                + durations[index]
                - TRANSITION_DURATION
            )

        # ==========================================================
        # BUILD AUDIO ACROSSFADE FILTER
        # ==========================================================

        current_audio = "[0:a]"

        for index in range(
            1,
            len(scene_videos),
        ):

            next_audio = (
                f"[{index}:a]"
            )

            output_label = (
                f"[a{index}]"
            )

            filter_parts.append(
                f"{current_audio}"
                f"{next_audio}"
                f"acrossfade="
                f"d={TRANSITION_DURATION:.3f}:"
                f"c1=tri:"
                f"c2=tri"
                f"{output_label}"
            )

            current_audio = (
                output_label
            )

        # ==========================================================
        # COMPLETE FILTER
        # ==========================================================

        filter_complex = (
            ";".join(
                filter_parts
            )
        )

        # ==========================================================
        # ADD FILTER
        # ==========================================================

        command.extend(
            [
                "-filter_complex",
                filter_complex,

                # --------------------------------------------------
                # FINAL VIDEO
                # --------------------------------------------------

                "-map",
                current_video,

                # --------------------------------------------------
                # FINAL AUDIO
                # --------------------------------------------------

                "-map",
                current_audio,

                # --------------------------------------------------
                # VIDEO ENCODING
                # --------------------------------------------------

                "-c:v",
                "libx264",

                "-preset",
                "medium",

                "-crf",
                "18",

                "-pix_fmt",
                "yuv420p",

                # --------------------------------------------------
                # AUDIO
                # --------------------------------------------------

                "-c:a",
                "aac",

                "-b:a",
                "192k",

                "-ar",
                "48000",

                # --------------------------------------------------
                # MP4
                # --------------------------------------------------

                "-movflags",
                "+faststart",

                str(output_file),
            ]
        )

        # ==========================================================
        # PRINT
        # ==========================================================

        self._print_command(
            command
        )

        print()
        print("=" * 80)
        print("MERGING SCENES WITH SMOOTH TRANSITIONS")
        print("=" * 80)

        for index, video in enumerate(
            scene_videos,
            start=1,
        ):

            print(
                f"Scene {index}: {video}"
            )

        print(
            f"Transition : "
            f"{TRANSITION_DURATION:.2f}s crossfade"
        )

        print(
            f"Output     : {output_file}"
        )

        print("=" * 80)
        print()

        # ==========================================================
        # RUN
        # ==========================================================

        subprocess.run(
            command,
            check=True,
        )

        # ==========================================================
        # VERIFY
        # ==========================================================

        if not output_file.exists():

            raise RuntimeError(
                "FFmpeg completed but merged video "
                "was not created:\n"
                f"{output_file}"
            )

        if output_file.stat().st_size <= 0:

            raise RuntimeError(
                "Merged video is empty:\n"
                f"{output_file}"
            )

        Logger.success(
            f"Merged video saved -> "
            f"{output_file}"
        )

        return output_file

    
    # ==========================================================
    # RENDER COMPLETE VERSE
    # ==========================================================

    def render_verse(
        self,
        scene_images,
        scene_audio_files,
        scene_subtitle_files,
        output_folder,
        scene_video_names=None,
        merge=True,
    ):
        """
        Production renderer for one complete verse.

        Expected order:

            Scene 1 image + audio + SRT
                -> scene1/scene1.mp4

            Scene 2 image + audio + SRT
                -> scene2/scene2.mp4

            Scene 3 image + audio + SRT
                -> scene3/scene3.mp4

            Scene 4 image + audio + SRT
                -> scene4/scene4.mp4

            scene1.mp4
            scene2.mp4
            scene3.mp4
            scene4.mp4
                -> merge_scenes()
                -> final/final_video.mp4

        Background music is added only by merge_scenes(), never to
        individual scene videos.

        Parameters
        ----------
        scene_images:
            Ordered iterable of 4 scene image paths.

        scene_audio_files:
            Ordered iterable of 4 narration MP3 paths.

        scene_subtitle_files:
            Ordered iterable of 4 SRT subtitle paths.

        output_folder:
            Verse folder, for example:
                output/chapter_001/verse_001

        scene_video_names:
            Optional names for the generated scene videos.
            Defaults to scene1.mp4 ... scene4.mp4.

        merge:
            If True, merge the four scene videos after rendering.
        """

        output_folder = Path(
            output_folder
        )

        output_folder.mkdir(
            parents=True,
            exist_ok=True,
        )

        # ------------------------------------------------------
        # Normalize inputs
        # ------------------------------------------------------

        scene_images = [
            Path(item)
            for item in scene_images
        ]

        scene_audio_files = [
            Path(item)
            for item in scene_audio_files
        ]

        scene_subtitle_files = [
            Path(item)
            for item in scene_subtitle_files
        ]

        if not (
            len(scene_images)
            == len(scene_audio_files)
            == len(scene_subtitle_files)
            == 4
        ):

            raise ValueError(
                "render_verse requires exactly "
                "4 scene images, 4 audio files, "
                "and 4 subtitle files."
            )

        if scene_video_names is None:

            scene_video_names = [
                f"scene{index}.mp4"
                for index in range(1, 5)
            ]

        if len(scene_video_names) != 4:

            raise ValueError(
                "scene_video_names must contain "
                "exactly 4 names."
            )

        # ------------------------------------------------------
        # Production header
        # ------------------------------------------------------

        print()
        print("=" * 80)
        print("SBG V3 — COMPLETE VERSE RENDER")
        print("=" * 80)
        print()
        print(
            f"Verse folder: {output_folder}"
        )
        print()

        scene_videos = []

        # ------------------------------------------------------
        # Render Scene 1 -> Scene 4
        # ------------------------------------------------------

        for index in range(4):

            scene_number = index + 1

            image_file = (
                scene_images[index]
            )

            audio_file = (
                scene_audio_files[index]
            )

            subtitle_file = (
                scene_subtitle_files[index]
            )

            scene_folder = (
                output_folder
                / f"scene{scene_number}"
            )

            scene_folder.mkdir(
                parents=True,
                exist_ok=True,
            )

            output_file = (
                scene_folder
                / scene_video_names[index]
            )

            print()
            print("-" * 80)
            print(
                f"SCENE {scene_number} / 4"
            )
            print("-" * 80)

            print(
                f"Image:     {image_file}"
            )

            print(
                f"Audio:     {audio_file}"
            )

            print(
                f"Subtitles: {subtitle_file}"
            )

            print(
                f"Output:    {output_file}"
            )

            # --------------------------------------------------
            # Validate before starting FFmpeg
            # --------------------------------------------------

            self._check_file(
                image_file,
                f"Scene {scene_number} image",
            )

            self._check_file(
                audio_file,
                f"Scene {scene_number} narration",
            )

            self._check_file(
                subtitle_file,
                f"Scene {scene_number} subtitles",
            )

            # --------------------------------------------------
            # Render
            # --------------------------------------------------

            # Scene 2 has the optional karaoke/highlight overlay.
            # Keep the existing render_scene() path for Scenes 1, 3 and 4.
            if scene_number == 2:

                shloka_overlay = (
                    scene_folder
                    / "shloka_overlay.webm"
                )

                if shloka_overlay.exists():

                    Logger.info(
                        "Scene 2 Shloka overlay detected."
                    )

                    rendered = self.render_scene_2(
                        image_file=image_file,
                        audio_file=audio_file,
                        subtitle_file=subtitle_file,
                        shloka_overlay=shloka_overlay,
                        output_file=output_file,
                    )

                else:

                    Logger.info(
                        "Scene 2 Shloka overlay not found; "
                        "rendering normal scene."
                    )

                    rendered = self.render_scene(
                        image_file=image_file,
                        audio_file=audio_file,
                        subtitle_file=subtitle_file,
                        output_file=output_file,
                    )

            else:

                rendered = self.render_scene(
                    image_file=image_file,
                    audio_file=audio_file,
                    subtitle_file=subtitle_file,
                    output_file=output_file,
                )

            rendered = self._check_file(
                rendered,
                f"Scene {scene_number} video",
            )

            scene_videos.append(
                rendered
            )

            print(
                f"✓ Scene {scene_number} complete"
            )

        # ------------------------------------------------------
        # Duration table
        # ------------------------------------------------------

        print()
        print("=" * 80)
        print("SCENE DURATIONS")
        print("=" * 80)

        self.print_scene_durations(
            scene_audio_files
        )

        # ------------------------------------------------------
        # Merge
        # ------------------------------------------------------

        final_video = None

        if merge:

            print()
            print("=" * 80)
            print("MERGING 4 SCENES")
            print("=" * 80)
            print()

            final_video = self.merge_scenes(
                scene_videos=scene_videos,
                output_folder=output_folder,
            )

        # ------------------------------------------------------
        # Final summary
        # ------------------------------------------------------

        print()
        print("=" * 80)
        print("VERSE RENDER COMPLETE")
        print("=" * 80)
        print()

        for index, scene_video in enumerate(
            scene_videos,
            start=1,
        ):

            print(
                f"Scene {index}: "
                f"{scene_video}"
            )

        if final_video is not None:

            print()
            print(
                f"FINAL VIDEO: "
                f"{final_video}"
            )

        print()

        return {
            "scene_videos": scene_videos,
            "final_video": final_video,
            "output_folder": output_folder,
        }

    # ==========================================================
    # SCENE DURATION TABLE
    # ==========================================================

    def get_scene_durations(
        self,
        audio_files,
    ):

        scene_data = []

        for index, audio_file in enumerate(
            audio_files,
            start=1,
        ):

            audio_file = self._check_file(
                audio_file,
                f"Scene {index} narration",
            )

            narration_duration = (
                self._audio_duration(
                    audio_file
                )
            )

            scene_data.append(
                {
                    "scene": index,
                    "narration": narration_duration,
                    "image_duration": narration_duration,
                }
            )

        return scene_data

    # ==========================================================
    # PRINT SCENE DURATION TABLE
    # ==========================================================

    def print_scene_durations(
        self,
        audio_files,
    ):

        scene_data = (
            self.get_scene_durations(
                audio_files
            )
        )

        print()

        print(
            f"{'Scene':<8}"
            f"{'Narration':>14}"
            f"{'Image duration':>20}"
        )

        print(
            "-" * 42
        )

        for scene in scene_data:

            print(
                f"{scene['scene']:<8}"
                f"{scene['narration']:>10.2f} sec"
                f"{scene['image_duration']:>16.2f} sec"
            )

        print()

        return scene_data

