"""
Video Renderer (V3)

Scene-based video rendering.

For each scene:

    fixed image
        +
    scene narration
        +
    scene subtitles
        ↓
    scene_video.mp4

Final render:

    scene1.mp4
    scene2.mp4
    scene3.mp4
    scene4.mp4
        +
    background music
        ↓
    final_video.mp4

Images are NEVER generated by this module.
"""

from pathlib import Path
import subprocess
import tempfile

from config import (
    FFMPEG_PATH,
    FFPROBE_PATH,
    BACKGROUND_MUSIC,
    BACKGROUND_MUSIC_VOLUME,
    VIDEO_WIDTH,
    VIDEO_HEIGHT,
    FPS,
)

from modules.logger import Logger


class VideoRenderer:

    # ==========================================================
    # SBG SUBTITLE STYLE
    # ==========================================================

    # Large enough for 1080x1920 Shorts
    SUBTITLE_FONT = "Arial"

    SUBTITLE_FONT_SIZE = 52

    SUBTITLE_BOLD = True

    # ASS uses BGR/hex formatting internally.
    # FFFFFF = white
    SUBTITLE_PRIMARY_COLOUR = "&H00FFFFFF"

    # Black outline
    SUBTITLE_OUTLINE_COLOUR = "&H00000000"

    # Slightly transparent black shadow
    SUBTITLE_SHADOW_COLOUR = "&H80000000"

    # Thick cinematic outline
    SUBTITLE_OUTLINE = 4

    # Shadow depth
    SUBTITLE_SHADOW = 2

    # 2 = centered
    SUBTITLE_ALIGNMENT = 2

    # Distance from bottom of video.
    #
    # 400-ish places subtitles in the lower-middle
    # rather than directly above YouTube controls.
    SUBTITLE_MARGIN_V = 390

    # Horizontal margins
    SUBTITLE_MARGIN_L = 90
    SUBTITLE_MARGIN_R = 90

    # ==========================================================
    # INITIALIZE
    # ==========================================================

    def __init__(self):

        self.ffmpeg = str(
            FFMPEG_PATH
        )

        self.ffprobe = str(
            FFPROBE_PATH
        )

    # ==========================================================
    # AUDIO DURATION
    # ==========================================================

    def _audio_duration(
        self,
        audio_file: Path,
    ) -> float:

        audio_file = Path(
            audio_file
        )

        command = [

            self.ffprobe,

            "-v",
            "error",

            "-show_entries",
            "format=duration",

            "-of",
            "default="
            "noprint_wrappers=1:"
            "nokey=1",

            str(audio_file),
        ]

        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            check=True,
        )

        value = (
            result.stdout
            .strip()
        )

        if not value:

            raise Exception(
                f"Could not determine audio duration:\n"
                f"{audio_file}"
            )

        duration = float(
            value
        )

        if duration <= 0:

            raise Exception(
                f"Audio has zero duration:\n"
                f"{audio_file}"
            )

        return duration

    # ==========================================================
    # CHECK FILE
    # ==========================================================

    def _check_file(
        self,
        file_path,
        description,
    ):

        file_path = Path(
            file_path
        )

        if not file_path.exists():

            raise FileNotFoundError(
                f"{description} not found:\n"
                f"{file_path}"
            )

        if file_path.stat().st_size <= 0:

            raise Exception(
                f"{description} is empty:\n"
                f"{file_path}"
            )

        return file_path

    # ==========================================================
    # ESCAPE FILTER PATH
    # ==========================================================

    def _escape_filter_path(
        self,
        file_path,
    ):

        path = str(
            Path(
                file_path
            ).resolve()
        )

        path = path.replace(
            "\\",
            "/",
        )

        path = path.replace(
            ":",
            "\\:",
        )

        path = path.replace(
            "'",
            "\\'",
        )

        return path

    # ==========================================================
    # PRINT FFMPEG COMMAND
    # ==========================================================

    def _print_command(
        self,
        command,
    ):

        print()
        print("=" * 80)
        print("FFMPEG COMMAND")
        print("=" * 80)

        print(
            " ".join(
                (
                    f'"{item}"'
                    if " " in str(item)
                    else str(item)
                )
                for item in command
            )
        )

        print("=" * 80)
        print()

    # ==========================================================
    # CREATE ASS SUBTITLE FILE
    # ==========================================================

    def _create_ass_subtitles(
        self,
        subtitle_file,
        ass_file,
    ):
        """
        Convert the generated SRT into an ASS subtitle file.

        ASS gives us much better control over:

        - Font
        - Size
        - Bold
        - Outline
        - Shadow
        - Position
        - Margins
        """

        subtitle_file = Path(
            subtitle_file
        )

        ass_file = Path(
            ass_file
        )

        ass_file.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        # ------------------------------------------------------
        # Read SRT
        # ------------------------------------------------------

        with open(
            subtitle_file,
            "r",
            encoding="utf-8-sig",
        ) as f:

            content = f.read()

        blocks = content.strip().split(
            "\n\n"
        )

        # ------------------------------------------------------
        # ASS header
        # ------------------------------------------------------

        lines = [

            "[Script Info]",

            "ScriptType: v4.00+",

            "PlayResX: 1080",

            "PlayResY: 1920",

            "ScaledBorderAndShadow: yes",

            "",

            "[V4+ Styles]",

            (
                "Format: "
                "Name,"
                "Fontname,"
                "Fontsize,"
                "PrimaryColour,"
                "SecondaryColour,"
                "OutlineColour,"
                "BackColour,"
                "Bold,"
                "Italic,"
                "Underline,"
                "StrikeOut,"
                "ScaleX,"
                "ScaleY,"
                "Spacing,"
                "Angle,"
                "BorderStyle,"
                "Outline,"
                "Shadow,"
                "Alignment,"
                "MarginL,"
                "MarginR,"
                "MarginV,"
                "Encoding"
            ),

            (
                "Style: Default,"
                f"{self.SUBTITLE_FONT},"
                f"{self.SUBTITLE_FONT_SIZE},"
                f"{self.SUBTITLE_PRIMARY_COLOUR},"
                "&H00000000,"
                f"{self.SUBTITLE_OUTLINE_COLOUR},"
                f"{self.SUBTITLE_SHADOW_COLOUR},"
                f"{-1 if self.SUBTITLE_BOLD else 0},"
                "0,"
                "0,"
                "0,"
                "100,"
                "100,"
                "0,"
                "0,"
                "1,"
                f"{self.SUBTITLE_OUTLINE},"
                f"{self.SUBTITLE_SHADOW},"
                f"{self.SUBTITLE_ALIGNMENT},"
                f"{self.SUBTITLE_MARGIN_L},"
                f"{self.SUBTITLE_MARGIN_R},"
                f"{self.SUBTITLE_MARGIN_V},"
                "1"
            ),

            "",

            "[Events]",

            (
                "Format: "
                "Layer,"
                "Start,"
                "End,"
                "Style,"
                "Name,"
                "MarginL,"
                "MarginR,"
                "MarginV,"
                "Effect,"
                "Text"
            ),
        ]

        # ------------------------------------------------------
        # Parse SRT blocks
        # ------------------------------------------------------

        for block in blocks:

            block_lines = block.splitlines()

            if len(block_lines) < 3:

                continue

            # --------------------------------------------------
            # Timing line
            # --------------------------------------------------

            timing_line = block_lines[1]

            if "-->" not in timing_line:

                continue

            start_text, end_text = (
                timing_line.split(
                    "-->",
                    1,
                )
            )

            start_text = (
                start_text.strip()
            )

            end_text = (
                end_text.strip()
            )

            start = (
                self._srt_to_ass_time(
                    start_text
                )
            )

            end = (
                self._srt_to_ass_time(
                    end_text
                )
            )

            # --------------------------------------------------
            # Subtitle text
            # --------------------------------------------------

            text = "\\N".join(
                block_lines[2:]
            )

            text = (
                text
                .replace(
                    "{",
                    "\\{",
                )
                .replace(
                    "}",
                    "\\}",
                )
            )

            # --------------------------------------------------
            # ASS event
            # --------------------------------------------------

            lines.append(
                (
                    "Dialogue: "
                    f"0,"
                    f"{start},"
                    f"{end},"
                    "Default,"
                    ","
                    "0,"
                    "0,"
                    "0,"
                    ","
                    f"{text}"
                )
            )

        # ------------------------------------------------------
        # Write ASS
        # ------------------------------------------------------

        with open(
            ass_file,
            "w",
            encoding="utf-8-sig",
            newline="\n",
        ) as f:

            f.write(
                "\n".join(
                    lines
                )
            )

        return ass_file

    # ==========================================================
    # SRT → ASS TIME
    # ==========================================================

    def _srt_to_ass_time(
        self,
        value,
    ):

        value = value.strip()

        # SRT:
        #
        # 00:00:02,500
        #
        # ASS:
        #
        # 0:00:02.50

        parts = value.split(
            ":"
        )

        if len(parts) != 3:

            raise ValueError(
                f"Invalid SRT timestamp: {value}"
            )

        hours = int(
            parts[0]
        )

        minutes = int(
            parts[1]
        )

        seconds_part = parts[2]

        if "," in seconds_part:

            seconds, milliseconds = (
                seconds_part.split(
                    ",",
                    1,
                )
            )

        else:

            seconds = seconds_part
            milliseconds = "0"

        seconds = int(
            seconds
        )

        milliseconds = int(
            milliseconds.ljust(
                3,
                "0",
            )[:3]
        )

        centiseconds = int(
            round(
                milliseconds
                / 10
            )
        )

        # Handle rounding to 100 centiseconds.
        if centiseconds >= 100:

            centiseconds = 0
            seconds += 1

        if seconds >= 60:

            seconds = 0
            minutes += 1

        if minutes >= 60:

            minutes = 0
            hours += 1

        return (
            f"{hours}:"
            f"{minutes:02d}:"
            f"{seconds:02d}."
            f"{centiseconds:02d}"
        )

    # ==========================================================
    # RENDER ONE SCENE
    # ==========================================================

    def render_scene(
        self,
        image_file,
        audio_file,
        subtitle_file,
        output_file,
    ):
        """
        Create one independent scene video.

        Image
            +
        scene narration
            +
        styled subtitles
            ↓
        scene_video.mp4
        """

        image_file = self._check_file(
            image_file,
            "Scene image",
        )

        audio_file = self._check_file(
            audio_file,
            "Scene narration",
        )

        subtitle_file = self._check_file(
            subtitle_file,
            "Scene subtitles",
        )

        output_file = Path(
            output_file
        )

        output_file.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        # ------------------------------------------------------
        # Exact narration duration
        # ------------------------------------------------------

        duration = (
            self._audio_duration(
                audio_file
            )
        )

        Logger.info(
            f"Scene duration : "
            f"{duration:.2f}s"
        )

        # ------------------------------------------------------
        # Create ASS subtitle file
        # ------------------------------------------------------

        ass_file = (
            output_file.parent
            / "subtitles.ass"
        )

        self._create_ass_subtitles(
            subtitle_file,
            ass_file,
        )

        ass_path = (
            self._escape_filter_path(
                ass_file
            )
        )

        # ------------------------------------------------------
        # Video filter
        # ------------------------------------------------------

        video_filter = (

            f"scale="
            f"{VIDEO_WIDTH}:"
            f"{VIDEO_HEIGHT}:"
            f"force_original_aspect_ratio=decrease,"

            f"pad="
            f"{VIDEO_WIDTH}:"
            f"{VIDEO_HEIGHT}:"
            f"(ow-iw)/2:"
            f"(oh-ih)/2,"

            f"fps={FPS},"

            "format=yuv420p,"

            "setsar=1,"

            f"ass='{ass_path}'"
        )

        # ------------------------------------------------------
        # FFmpeg command
        # ------------------------------------------------------

        command = [

            self.ffmpeg,

            "-y",

            # --------------------------------------------------
            # Fixed image
            # --------------------------------------------------

            "-loop",
            "1",

            "-i",
            str(image_file),

            # --------------------------------------------------
            # Narration
            # --------------------------------------------------

            "-i",
            str(audio_file),

            # --------------------------------------------------
            # Video filter
            # --------------------------------------------------

            "-vf",
            video_filter,

            # --------------------------------------------------
            # Mapping
            # --------------------------------------------------

            "-map",
            "0:v",

            "-map",
            "1:a",

            # --------------------------------------------------
            # Video
            # --------------------------------------------------

            "-c:v",
            "libx264",

            "-preset",
            "medium",

            "-crf",
            "18",

            "-pix_fmt",
            "yuv420p",

            # --------------------------------------------------
            # Audio
            # --------------------------------------------------

            "-c:a",
            "aac",

            "-b:a",
            "192k",

            "-ar",
            "48000",

            # --------------------------------------------------
            # Exact scene duration
            # --------------------------------------------------

            "-t",
            f"{duration:.6f}",

            # --------------------------------------------------
            # MP4
            # --------------------------------------------------

            "-movflags",
            "+faststart",

            str(output_file),
        ]

        self._print_command(
            command
        )

        Logger.info(
            f"Rendering scene -> "
            f"{output_file}"
        )

        subprocess.run(
            command,
            check=True,
        )

        # ------------------------------------------------------
        # Verify output
        # ------------------------------------------------------

        if not output_file.exists():

            raise Exception(
                "FFmpeg completed but scene "
                "video was not created:\n"
                f"{output_file}"
            )

        if output_file.stat().st_size <= 0:

            raise Exception(
                f"Scene video is empty:\n"
                f"{output_file}"
            )

        Logger.success(
            f"Scene video saved -> "
            f"{output_file}"
        )

        return output_file

    # ==========================================================
    # MERGE SCENE VIDEOS
    # ==========================================================

    def merge_scenes(
        self,
        scene_videos,
        output_folder,
    ):
        """
        Concatenate independent scene videos.

        Background music is added ONLY here.
        """

        if not scene_videos:

            raise Exception(
                "No scene videos supplied."
            )

        output_folder = Path(
            output_folder
        )

        output_folder.mkdir(
            parents=True,
            exist_ok=True,
        )

        final_folder = (
            output_folder
            / "final"
        )

        final_folder.mkdir(
            parents=True,
            exist_ok=True,
        )

        output_file = (
            final_folder
            / "final_video.mp4"
        )

        # ------------------------------------------------------
        # Validate scene videos
        # ------------------------------------------------------

        scene_videos = [

            self._check_file(
                video,
                f"Scene video {index}",
            )

            for index, video
            in enumerate(
                scene_videos,
                start=1,
            )
        ]

        # ------------------------------------------------------
        # Create concat list
        # ------------------------------------------------------

        concat_file = (
            final_folder
            / "scenes.txt"
        )

        with open(
            concat_file,
            "w",
            encoding="utf-8",
        ) as f:

            for video in scene_videos:

                video_path = (
                    video
                    .resolve()
                    .as_posix()
                )

                video_path = (
                    video_path.replace(
                        "'",
                        "'\\''",
                    )
                )

                f.write(
                    f"file '{video_path}'\n"
                )

        # ======================================================
        # STEP 1 — CONCATENATE
        # ======================================================

        merged_video = (
            final_folder
            / "merged_video.mp4"
        )

        concat_command = [

            self.ffmpeg,

            "-y",

            "-f",
            "concat",

            "-safe",
            "0",

            "-i",
            str(concat_file),

            "-c",
            "copy",

            "-movflags",
            "+faststart",

            str(merged_video),
        ]

        self._print_command(
            concat_command
        )

        Logger.info(
            "Merging scene videos..."
        )

        subprocess.run(
            concat_command,
            check=True,
        )

        if not merged_video.exists():

            raise Exception(
                "Merged video was not created."
            )

        # ======================================================
        # STEP 2 — BACKGROUND MUSIC
        # ======================================================

        music_file = Path(
            BACKGROUND_MUSIC
        )

        music_exists = (

            music_file.exists()

            and music_file.stat().st_size > 0

        )

        if music_exists:

            Logger.info(
                "Adding background music..."
            )

            music_volume = float(
                BACKGROUND_MUSIC_VOLUME
            )

            music_command = [

                self.ffmpeg,

                "-y",

                # ------------------------------------------------
                # Narration video
                # ------------------------------------------------

                "-i",
                str(merged_video),

                # ------------------------------------------------
                # Loop music
                # ------------------------------------------------

                "-stream_loop",
                "-1",

                "-i",
                str(music_file),

                # ------------------------------------------------
                # Audio mix
                # ------------------------------------------------

                "-filter_complex",

                (
                    "[1:a]"
                    f"volume={music_volume}"
                    "[music];"

                    "[0:a][music]"
                    "amix="
                    "inputs=2:"
                    "duration=first:"
                    "dropout_transition=2"
                    "[aout]"
                ),

                # ------------------------------------------------
                # Video
                # ------------------------------------------------

                "-map",
                "0:v",

                # ------------------------------------------------
                # Mixed audio
                # ------------------------------------------------

                "-map",
                "[aout]",

                "-c:v",
                "copy",

                "-c:a",
                "aac",

                "-b:a",
                "192k",

                "-ar",
                "48000",

                "-movflags",
                "+faststart",

                str(output_file),
            ]

            self._print_command(
                music_command
            )

            subprocess.run(
                music_command,
                check=True,
            )

        else:

            Logger.info(
                "Background music not found."
            )

            merged_video.replace(
                output_file
            )

        # ------------------------------------------------------
        # Verify final
        # ------------------------------------------------------

        if not output_file.exists():

            raise Exception(
                "Final video was not created."
            )

        if output_file.stat().st_size <= 0:

            raise Exception(
                "Final video is empty."
            )

        Logger.success(
            f"Final video saved -> "
            f"{output_file}"
        )

        Logger.success(
            "Scene subtitles -> "
            "STYLED / BURNED IN"
        )

        if music_exists:

            Logger.success(
                "Background music -> ON"
            )

        else:

            Logger.info(
                "Background music -> OFF"
            )

        return output_file

    # ==========================================================
    # SCENE DURATION TABLE
    # ==========================================================

    def get_scene_durations(
        self,
        audio_files,
    ):

        scene_data = []

        for index, audio_file in enumerate(
            audio_files,
            start=1,
        ):

            audio_file = self._check_file(
                audio_file,
                f"Scene {index} narration",
            )

            narration_duration = (
                self._audio_duration(
                    audio_file
                )
            )

            scene_data.append(
                {
                    "scene": index,
                    "narration": narration_duration,
                    "image_duration": narration_duration,
                }
            )

        return scene_data

    # ==========================================================
    # PRINT SCENE DURATION TABLE
    # ==========================================================

    def print_scene_durations(
        self,
        audio_files,
    ):

        scene_data = (
            self.get_scene_durations(
                audio_files
            )
        )

        print()

        print(
            f"{'Scene':<8}"
            f"{'Narration':>14}"
            f"{'Image duration':>20}"
        )

        print(
            "-" * 42
        )

        for scene in scene_data:

            print(
                f"{scene['scene']:<8}"
                f"{scene['narration']:>10.2f} sec"
                f"{scene['image_duration']:>16.2f} sec"
            )

        print()

        return scene_data